# Generated by Django 3.0.3 on 2020-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainJoy', '0002_kontakti_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='njoftimet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='kontakti',
        ),
    ]
