# Generated by Django 3.0.3 on 2020-04-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainJoy', '0003_auto_20200408_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='njoftimet',
        ),
    ]
