# Generated by Django 3.0.3 on 2020-04-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainJoy', '0005_njoftimet'),
    ]

    operations = [
        migrations.AddField(
            model_name='njoftimet',
            name='first_name',
            field=models.CharField(default='Emri', max_length=100),
        ),
        migrations.AddField(
            model_name='njoftimet',
            name='last_name',
            field=models.CharField(default='Mbiemri', max_length=100),
        ),
        migrations.AddField(
            model_name='njoftimet',
            name='upload',
            field=models.FileField(default='upload', upload_to='uploads'),
        ),
    ]
