# Generated by Django 3.0.3 on 2020-04-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainJoy', '0006_auto_20200408_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='njoftimet',
            name='upload',
        ),
        migrations.AddField(
            model_name='njoftimet',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='njoftimet',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='njoftimet',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
