# Generated by Django 3.0.3 on 2020-04-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainJoy', '0009_auto_20200408_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kursi',
            old_name='modulet',
            new_name='moduli',
        ),
    ]
