# Generated by Django 3.0.3 on 2020-04-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainJoy', '0010_auto_20200412_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
