# Generated by Django 3.0.3 on 2020-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainJoy', '0011_auto_20200412_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='njoftimet',
            name='url',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
